function init_button_degxh04i(widget) {
    if (widget.isInitialized()) {
        return;
    }
    widget.initDateChanged('1758324885');
    widget.initCss('#{$buttonid} > div {border-radius:50%; margin:0; padding:0;}#{$buttonid} .circleChatButtonWrap:hover {box-shadow:0 2px 10px rgba(0,0,0,0.6) !important;}#{$buttonid} .circleChatButtonWrap:hover .circleChatBubbleContent {-webkit-transform: rotate(-45deg) !important; -moz-transform: rotate(-45deg) !important; -o-transform: rotate(-45deg) !important; transform: rotate(-45deg) !important;}#{$buttonid} .circleChatButtonWrap:hover .circleChatDot1 {border-radius:0 !important; width:0 !important; height:0 !important; background:transparent !important; border-style: solid !important; border-width: 2.5px 4px 2.5px 0 !important; border-color: transparent #820FF5 transparent transparent !important; left:3px !important;}#{$buttonid} .circleChatButtonWrap:hover .circleChatDot2 {border-radius:0 !important; width:14px !important; left:8px !important; height:5px !important;}#{$buttonid} .circleChatButtonWrap:hover .circleChatDot3 {border-radius:0 1px 1px 0 !important; width:4px !important; height:5px !important; left:23px !important;}@media print { #{$buttonid} { display:none}}   ');
    widget.initHtml('<div style="bottom: 20px;right:20px;-ms-transform-origin:100% 100%; -webkit-transform-origin:100% 100%; transform-origin:100% 100%; z-index: 999997; position: fixed;"><!-- Circle --><div class=\'circleChatButtonWrap\' style=\'display: inline-block; margin:0; padding:0; border:0; border-radius:50%; position:relative;background:#860EAF;background: -moz-linear-gradient(-45deg, #860EAF 0%, #FF0505 100%);background: -webkit-linear-gradient(-45deg, #860EAF 0%, #FF0505 100%);background: linear-gradient(135deg, #860EAF 0%, #FF0505 100%);width:65px; height:65px; box-sizing:border-box; cursor:pointer; -webkit-transition: all ease 1s; -moz-transition: all ease 1s; -o-transition: all ease 1s; transition: all ease 1s; box-shadow:0 3px 10px rgba(0,0,0,0.3);\'><div class=\'circleChatBubble\' style=\'background:#FFFFFF; border-radius:7px 7px 7px 0; width:31px; height:31px; position:absolute; top:17px; left:17px; box-shadow: 0 2px 5px rgba(0,0,0,0.2);\'></div><div class=\'circleChatBubbleTriangle\' style=\'border-color: transparent transparent transparent #FFFFFF; position:absolute; display:block; width:0; height:0; border-style: solid; border-width: 0 0 10px 10px; left:17px; bottom:12px;\'></div><div class=\'circleChatBubbleContent\' style=\'transform-origin:50% 50%; width:31px; height:5px; position:absolute; top:31px; left:17px; overflow:hidden; -webkit-transform: rotate(0deg); -moz-transform: rotate(0deg); -o-transform: rotate(0deg); -webkit-transition: all ease 0.2s;  -moz-transition: all ease 0.2s; -o-transition: all ease 0.2s; transition: all ease 0.2s;\'><div class=\'circleChatDot circleChatDot1\' style=\'left:7px; width:4px; height:4px; top:0; background:#820FF5; border-radius:50%; position:absolute; -webkit-transition: all ease 0.2s; -moz-transition: all ease 0.2s; -o-transition: all ease 0.2s; transition: all ease 0.2s;\'></div><div class=\'circleChatDot circleChatDot2\' style=\'left:14px; width:4px; height:4px; top:0; background:#820FF5; border-radius:50%; position:absolute; -webkit-transition: all ease 0.2s; -moz-transition: all ease 0.2s; -o-transition: all ease 0.2s; transition: all ease 0.2s;\'></div><div class=\'circleChatDot circleChatDot3\' style=\'left:21px; width:4px; height:4px; top:0; background:#820FF5; border-radius:50%; position:absolute; -webkit-transition: all ease 0.2s; -moz-transition: all ease 0.2s; -o-transition: all ease 0.2s; transition: all ease 0.2s;\'></div></div></div></div>');
    widget.setTitleName('Live chat button');
    widget.initEmbeddedChat('scripts/generateWidget.php?v=5.57.3.8&t=1758324885&cwid=degxh04i&cwt=chat', '350', '450', 'BR', '');
    widget.initPreChatForm('scripts/generateWidget.php?v=5.57.3.8&t=1758324885&cwid=degxh04i&cwt=onlineform', '350', '600', 'BR', '', '');
    widget.onOnline();

}
var widgets = LiveAgent.instance.getWidgetsByWidgetId('degxh04i');
var widgetsLength = widgets.length;
for (var i = 0; i < widgetsLength; i++) {
    init_button_degxh04i(widgets[i]);
}
